-- AlterTable
ALTER TABLE "Venta" ADD COLUMN     "etapaId" INTEGER NOT NULL DEFAULT 1;

-- AddForeignKey
ALTER TABLE "Venta" ADD CONSTRAINT "Venta_etapaId_fkey" FOREIGN KEY ("etapaId") REFERENCES "Etapa"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
